name: Push to Code repo

on:
  push:
    #paths:
     # - '/content' 

jobs:
  push-to-repo-a:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Content  to Code repo
      run: cp -r content/ repo-a/content/

    - name: Commit and Push  to Code repo
      run: |
        cd repo-a
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add -A
        git commit -m "Update content folder"
        git push
