name: Publish to Medium

"on":
  push:
    branches:
      - main
    #paths:
      #- 'posts/**'  

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creates output folder and remove markdown
        run:  |
              mkdir output
              cp -r content output
      - name: Set Up Private Key 
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{secret.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
            sd .ssh
            ls
