name: Publish to Medium

"on":
  push:
    branches:
      - main
    #paths: 
      #- 'posts/**'  

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creates output folder and remove markdown
        run:  |
              mkdir output
              cp -r content output
      - uses: actions/checkout@v2
      - name: Set Up Private Key 
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
            git config --global user.email "amine.boukhari@tsplus.net"
            git config --global user.name "amineBoukhari"
            git submodule add git@github.com:jwts-dev/tsplus-net.git TSplus_Astro
            cp content/blog/* TSplus_Astro/src/content/blog
            cd TSplus_Astro
            
            if [[ -n $(git status -s) ]]; then
                git add .
                git commit -m "Update submodule and blog content"
                git push
            else
                echo "No changes to commit."
            fi

