name: Run Python Script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change to the desired Python version

      - name: Install Python dependencies
        run: |
          pip install beautifulsoup4
          pip install requests
      - name: Run Python script
        run: |
          python scrape.py  # Replace with your actual Python script name

      - name: Set Up Users info
        run: |
            git config --global user.email "amine.boukhari@tsplus.net"
            git config --global user.name "amineBoukhari"

      - name: push modifications
        run :	 |   
          if [[ -n $(git status -s) ]]; then
              git add .
              git commit -m "Update submodule and blog content"
              git push
          else
              echo "No changes to commit."
          fi
