name: Chat with GPT

on: [push]

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14' # Use the Node.js version compatible with your project

    - name: Read file content
      id: readfile
      run: |
        echo "::set-output name=content::$(node readFile.js blogs/2023-cyberthreats-threads-the-advanced-security-response.md)"

    - name: Send content to ChatGPT
      run: |
          CONTENT="${{ steps.readfile.outputs.content }}"
          echo "Sending the following content to ChatGPT:"
          echo "$CONTENT"

    - name: Send message to GPT
      run: |
        ls   
        curl -X POST \
        https://api.openai.com/v1/chat/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.GPT }}" \
        -d '{
             "model": "gpt-3.5-turbo",
             "messages": [{"role": "user", "content": "translate this to french : $CONTENT "}],
             "temperature": 0.7
           }'
      env:
        OPENAI_KEY: ${{ secrets.GPT }}
