name: Chat with GPT

on: [push]

jobs:
  chat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14' # Use the Node.js version compatible with your project
    - name: Send message to GPT
      run: |
          ls
          curl -X POST \
          curl https://api.openai.com/v1/chat/completions  \
          -H "Authorization: Bearer ${{secrets.GPT}}" \
          -F purpose="fine-tune" \
          -F file= @blog/2023-cyberthreats-threads-the-advanced-security-response.md
          -d '{
            "model": "gpt-3.5-turbo",
            "messages": [{"role": "user", "content": "translate the given file to french"}],
            "temperature": 0.7
          }'


      env:
        OPENAI_KEY: ${{ secrets.GPT }}
