jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: yunwei37/OpenAI-Continuous-Translator@master
      with:
          git_repo_url: https://github.com/amineBoukhari/TSplus-content.git
          api_key: ${{ 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 }}
          source_language: 'en' # Replace 'en' with your desired source language code
          target_language: 'fh' # Replace 'zh' with your desired target language code
          # Add other inputs as needed
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
