name: Push to Code repo

on:
  push:
    #paths:
     # - '/content' 

jobs:
  push-to-repo-code:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Content  to Code repo
      run: |
           ls
           cp -r https://github.com/amineBoukhari/TSplus-content/tree/7509d15c3bb50b065a3c0ccd5a0aa57d3120c64b/content/blog1.md TSplus_code/content/

    - name: Commit and Push  to Code repo
      run: |
        cd repo-a
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add -A
        git commit -m "Update content folder"
        git push
