name: Push to Code repo

on:
  push:
    #paths:
     # - '/content' 

jobs:
  push-to-repo-code:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Content  to Code repo
      run: |
        ls -la
         
