name: Publish to Medium

"on":
  push:
    branches:
      - main
    #paths:
      #- 'posts/**'  

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creates output folder and remove markdown
        run:  |
              mkdir output
              cp -r content output
      - name: Pushes to public repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: SHA256:Q1gtkgOPVAbCFPfODS5ar97axsBqjaQsCodIgXq3roM

        with:
          source-directory: output/
          destination-github-username: 'amineBoukhari'
          destination-repository-name: 'TSplus_code'
          user-email: amine.boukhari@tsplus.net
          commit-message: pushed from $GITHUB_REF
          target-branch: main
